name = "scheduling-app"
main = "dist/worker.js"
compatibility_date = "2023-12-01"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "scheduling-db"
database_id = "your-d1-database-id"

[build]
command = "npm run build:worker"